apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service: frontend
#  namespace: default
#  selfLink: /api/v1/namespaces/default/services/frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
  selector:
    service: frontend
  type: ClusterIP
